In [41]:
import numpy as np
import pandas as pd
import requests
from requests.auth import HTTPBasicAuth
import json
import os

In [42]:
# Функция считающая процентиль для агрегации
def percentile(n):
    def percentile_(sroki):
        return np.percentile(sroki, n)
    percentile_.__name__ = 'percentile_%s' % n
    return percentile_

In [43]:
def object_to_date(deliv_time, deliv_time_features, name_features):
    deliv_time[name_features] = pd.to_datetime(
        deliv_time_features,
        format="%Y-%m-%dT%H:%M:%S"
    )

In [44]:
headers = {
    'Content-type': 'application/json',
}
data = {
    "НачалоПериода": "19.09.2018 0:00:00",
    "КонецПериода": "19.12.2020 23:59:59",
    "ВидПоставкиТоваров": "От поставщиков"
}

In [45]:
def load_data_from_api(service_url):
    response = requests.post(
        service_url,
        auth=HTTPBasicAuth('Web', 'WebMarket'),
        data=json.dumps(data),
        headers=headers
    )
    return response.json()

In [46]:
list_to_drop = [
    'warehouse_id', 'item_id', 'fabricator_id', 'item_id',
    'item_guid', 'item_charac_id', 'item_charac_guid'
]

In [47]:
# Посмотрим локальную директорию
os.listdir('/Users/2/PycharmProjects/ordersprediction/files')

['delivery_time.csv', 'statistics.json']

In [48]:
# Загрузим датасет
deliv = pd.read_csv('/Users/2/PycharmProjects/ordersprediction/files/delivery_time.csv')

In [49]:
# Проверим 5 рандомных записей
deliv.sample(5)

,date_receipt,warehouse_id,warehouse_guid,item_id,item_guid,item_charac_id,item_charac_guid,date_orders,fabricator_id,fabricator_guid,IsFromSupplier
308,2020-12-19T00:00:00,15,f6548095-c106-11e0-8baa-00262d126e8b,105055,c2a1ef3b-3ffc-11e9-a2d4-000c29675a27,1,cb310891-3ffc-11e9-a2d4-000c29675a27,2020-12-19T00:00:00,16,5464cd6c-b080-11e2-85e4-00155d006702,0
5435,2020-12-22T00:00:00,15,f6548095-c106-11e0-8baa-00262d126e8b,44840,82352cc7-a0bd-11e6-80d2-00155d000e07,1,48dbf4c6-a0bf-11e6-80d2-00155d000e07,2020-12-09T00:00:00,16,5464cd6c-b080-11e2-85e4-00155d006702,1
366,2020-12-19T00:00:00,15,f6548095-c106-11e0-8baa-00262d126e8b,54532,fe0b375e-3c4e-11e7-80d9-00155d000e07,1,fe0b3760-3c4e-11e7-80d9-00155d000e07,2020-12-19T00:00:00,22,1baec3fb-d646-11e2-b394-f46d04736e4a,0
5678,2020-12-22T00:00:00,15,f6548095-c106-11e0-8baa-00262d126e8b,105059,13258675-3ffd-11e9-a2d4-000c29675a27,1,1c460fab-3ffd-11e9-a2d4-000c29675a27,2020-12-13T00:00:00,16,5464cd6c-b080-11e2-85e4-00155d006702,1
3431,2020-12-19T00:00:00,15,f6548095-c106-11e0-8baa-00262d126e8b,42714,53c7dbe5-69f1-11e6-80d2-00155d000e07,2,315fe7a3-e466-11e6-80d6-00155d000e02,2020-12-02T00:00:00,22,1baec3fb-d646-11e2-b394-f46d04736e4a,1

In [50]:
# Дропним ненужные фичи и переменуем нужные
deliv['OFFER_ID'] = deliv[['item_guid', 'item_charac_guid']].apply(lambda x: '#'.join(x), axis=1)
deliv.drop(list_to_drop, axis=1, inplace=True)
deliv.rename(
    columns={
        'warehouse_guid': 'PlacementToId',
        'fabricator_guid': 'PlacementFromId'
    }, inplace=True
)

In [51]:
# Посмотрим число уникальных IsFromSupplier
deliv.IsFromSupplier.unique()

array([0, 1], dtype=int64)

In [52]:
# Выберем только IsFromSupplier == 1
deliv = deliv.loc[deliv['IsFromSupplier'] == 1]

In [53]:
# Посмотрим число уникальных IsFromSupplier
deliv.IsFromSupplier.unique()

array([1], dtype=int64)

In [54]:
# Посмотрим на результат
deliv.sample(10)

,date_receipt,PlacementToId,date_orders,PlacementFromId,IsFromSupplier,OFFER_ID
4246,2020-12-20T00:00:00,a2f89531-75de-11e8-a2c3-000c29dcdf3d,2020-12-17T00:00:00,1a46cb6b-c740-11e6-80d4-00155d000e07,1,1d178c1e-b155-11ea-ab38-000c29a01421#2a0c4004-...
4925,2020-12-21T00:00:00,f6548095-c106-11e0-8baa-00262d126e8b,2020-11-23T00:00:00,c511cfeb-b583-11e7-ab58-000c2945f18b,1,4e6927f3-05f0-11e9-a2c7-00505607eae9#4e6927f5-...
5557,2020-12-22T00:00:00,f6548095-c106-11e0-8baa-00262d126e8b,2020-11-26T00:00:00,5464cd6c-b080-11e2-85e4-00155d006702,1,ca1a7d4c-3ffb-11e9-a2d4-000c29675a27#ca1a7d50-...
5833,2020-12-22T00:00:00,f6548095-c106-11e0-8baa-00262d126e8b,2020-11-29T00:00:00,799adf67-cb79-11e6-80d4-00155d000e07,1,e02f3e45-69c4-11ea-a307-00505607eae9#3d6a071e-...
5407,2020-12-22T00:00:00,f6548095-c106-11e0-8baa-00262d126e8b,2020-12-05T00:00:00,5464cd6c-b080-11e2-85e4-00155d006702,1,82352cc4-a0bd-11e6-80d2-00155d000e07#82352cc6-...
3838,2020-12-20T00:00:00,f6548095-c106-11e0-8baa-00262d126e8b,2020-12-10T00:00:00,3146f195-f3f4-11e9-a2dc-000c29675a27,1,a484eac6-fb04-11e9-a2e0-00505607eae9#a484eac8-...
5671,2020-12-22T00:00:00,f6548095-c106-11e0-8baa-00262d126e8b,2020-12-10T00:00:00,5464cd6c-b080-11e2-85e4-00155d006702,1,13258675-3ffd-11e9-a2d4-000c29675a27#1c460fab-...
5074,2020-12-21T00:00:00,03f70e82-3e4e-11e8-a2bb-000c29dcdf3d,2020-12-01T00:00:00,1b38fc80-5d45-11ea-a307-00505607eae9,1,c7a1bdc3-9124-11ea-ab37-000c29a01421#c7a1bdc9-...
4663,2020-12-21T00:00:00,4bc4d898-ec0e-11e9-a2dc-000c29675a27,2020-11-24T00:00:00,5464cd6c-b080-11e2-85e4-00155d006702,1,62bd4980-3ffd-11e9-a2d4-000c29675a27#68bf1a67-...
5337,2020-12-22T00:00:00,f6548095-c106-11e0-8baa-00262d126e8b,2020-11-16T00:00:00,5464cd6c-b080-11e2-85e4-00155d006702,1,a9cccf97-a0b7-11e6-80d2-00155d000e07#a9cccf99-...

In [58]:
deliv.PlacementFromId.unique()

array(['1baec3fb-d646-11e2-b394-f46d04736e4a',
       '4038bae0-e7bc-11e6-80d6-00155d000e02',
       '4bc0ce74-bb0d-11e3-9031-f46d04736e4a',
       '6903d81b-4454-11e7-8b3e-902b34d492d7',
       '3904ba5a-3bb0-11e7-80d9-00155d000e07',
       '4c809680-62ab-11e6-80d1-00155d000e07',
       '14caa9a8-e4cd-11e9-a2db-000c29675a27',
       '343563b8-3843-11ea-a2fc-00505607eae9',
       '3588e768-874a-11e3-a732-f46d04736e4a',
       '7e1e555b-557c-11e7-ab48-000c2945f18b',
       '1a46cb6b-c740-11e6-80d4-00155d000e07',
       '14c48fc0-5450-11e3-9599-f46d04736e4a',
       'a86462dd-0d90-11e4-95a7-f46d04736e4a',
       'b27d9c73-464d-11ea-a305-00505607eae9',
       '70509cad-bd19-11ea-ab38-000c29a01421',
       'a951b06e-f42d-11e6-80d6-00155d000e02',
       '085f3915-84c3-11e2-be7c-f46d04736e4a',
       'df630ac8-c708-11e8-a2c1-00505607eae9',
       '00bae129-1faf-11e9-a2c8-00505607eae9',
       'ce2d4ffe-2242-11e4-8146-f46d04736e4a',
       '4ff3bba1-74fa-11e2-b38d-f46d04736e4a',
       '4c377d09-31b5-11e4-980e-f46d04736e4a',
       '1257e922-1156-11e8-ab61-000c2945f18b',
       '18a0bfc7-e9d0-11e6-80d6-00155d000e02',
       '9e909d75-d372-11e7-ab61-000c2945f18b',
       '9850e147-7c17-11e7-ab50-000c2945f18b',
       '4f3775d1-499d-11ea-a305-00505607eae9',
       '7cbe713b-f143-11e8-a2c4-00505607eae9',
       '5464cd6c-b080-11e2-85e4-00155d006702',
       '86a0fcd5-6747-11e9-a2d6-000c29675a31',
       '45f0f6f5-00d3-11e8-ab61-000c2945f18b',
       '5a74aae8-4f7d-11e9-a2d5-000c29675a27',
       'ae96c6ed-8a02-11ea-ab36-000c29a01421',
       'a2a1ac70-53c6-11e6-80d0-00155d000e02',
       '0aaf506e-1b66-11e3-92f5-f46d04736e4a',
       'e5534a6a-8e2d-11e8-a2c6-000c29dcdf3d',
       'b2641f5d-dfa9-11e5-80cc-00155d000e07',
       '75151b2f-c5e7-11e6-80d4-00155d000e07',
       'f2af891e-dadc-11e4-b6a0-f46d04736e4a',
       'f9b0b553-7072-11e8-a2c3-000c29dcdf3d',
       '2b673bbe-891c-11e5-952f-f46d04736e4a',
       '6e75c97a-b7de-11e7-ab58-000c2945f18b',
       '45f0f6fd-00d3-11e8-ab61-000c2945f18b',
       '1b8f04e0-6fe6-11ea-a307-00505607eae9',
       'b729c8e2-5d70-11e7-ab48-000c2945f18b',
       '2c583f03-af1c-11e3-ad1c-f46d04736e4a',
       '58b8ed29-8330-11e8-a2c4-000c29dcdf3d',
       'af116c81-8da4-11e9-a2d7-000c29675a27',
       'c511cfeb-b583-11e7-ab58-000c2945f18b',
       '02b9c0d2-d8f8-11e4-bb70-f46d04736e4a',
       '4f1bd032-6153-11e7-ab48-000c2945f18b',
       '0cfcbd8c-4682-11e7-ab48-000c2945f18b',
       '365692a4-ce12-11e9-a2d7-000c29675a27',
       '9dc7788c-968e-48ec-98cc-56dcd36a8244',
       '9442f574-df98-11e9-a2d9-000c29675a27',
       '3c49d1fe-a94e-11e9-a2d7-000c29675a27',
       '48452082-00c4-11e8-ab61-000c2945f18b',
       '901430d2-e5ae-11e4-afaf-f46d04736e4a',
       'f0287a2c-d6a6-11e4-891c-f46d04736e4a',
       '4877b0e4-acc0-11e7-ab58-000c2945f18b',
       '8d8c0f75-5c1a-11e9-a2d6-000c29675a27',
       'af888d27-c2ed-11e8-a2c1-00505607eae9',
       'd57acb49-fc8b-11e9-a2e0-00505607eae9',
       '0c67dbda-bd97-11e9-a2d7-000c29675a27',
       '86623a51-217a-11ea-a2f3-00505607eae9',
       '799adf67-cb79-11e6-80d4-00155d000e07',
       '9afa19ce-7902-11e8-a2c4-000c29dcdf3d',
       '6a9802e1-3abc-11e7-80d9-00155d000e07',
       'c6014a86-283c-11e8-ab63-000c2945f18b',
       '3146f195-f3f4-11e9-a2dc-000c29675a27',
       '0bd20a68-fc75-11e8-a2c6-00505607eae9',
       '23ab02bc-c829-11e2-a84b-00155d006702',
       '1f688887-b7fe-11e8-a2c1-00505607eae9',
       '0891ebf4-8f82-11ea-ab37-000c29a01421',
       'b0ed0281-e9f1-11e7-ab61-000c2945f18b',
       '75515f2a-58da-11e8-a2c3-000c29dcdf3d',
       '5d18d766-18f4-11e7-80d7-00155d000e07',
       '00da2f6e-7d37-11e4-b062-f46d04736e4a',
       'bfe12025-6878-11e8-a2c3-000c29dcdf3d',
       'b1a3e91d-b052-11ea-ab38-000c29a01421',
       'e85993bb-6ccb-11ea-a307-00505607eae9',
       '2bf0ed6b-a5b1-11e2-911e-f46d04736e4a',
       '4e749769-f4bd-11e9-a2dc-000c29675a27',
       '4c52bb13-f007-11e9-a2dc-000c29675a27',
       'd7fcf4f4-5be2-11e7-ab48-000c2945f18b',
       'c0561a52-0661-11e3-82ab-f46d04736e4a',
       'd86359ec-e37f-11ea-ab3c-000c29a0142b',
       '5100792b-cabc-11e8-a2c1-00505607eae9',
       '97f574cd-5de7-11e5-91be-f46d04736e4a',
       '29f605cb-dcca-11e8-a2c4-00505607eae9',
       'e697120b-6c63-11e7-ab50-000c2945f18b',
       '826621cb-b719-11e8-a2c1-00505607eae9',
       'd035d76b-6006-11e9-a2d6-000c29675a27',
       '3fbbaba6-069e-11ea-a2e4-00505607eae9',
       'c12c2185-67f5-11e9-a2d6-000c29675a31',
       'e529c7a4-a5c2-11e8-a2c0-00505607eae9',
       '3e575ca9-d8d8-11e8-a2c4-00505607eae9',
       '723a36a5-c498-11e9-a2d7-000c29675a27',
       '6e4b62f7-8af4-11e2-8663-f46d04736e4a',
       'eb8d6128-ebef-11e9-a2dc-000c29675a27',
       'dbab9fa8-89e9-11ea-ab36-000c29a01421',
       '8d8d3786-cb4d-11e7-ab61-000c2945f18b',
       '0db432a9-1957-11e9-a2c8-00505607eae9',
       '60ac5404-a449-11e7-ab54-000c2945f18b',
       '8e9c0f70-0732-11e4-a8a5-f46d04736e4a',
       'bddfed39-7e97-11e8-a2c4-000c29dcdf3d',
       '668b68e9-faa9-11e3-a8a5-f46d04736e4a',
       'd6d733e1-3c8c-11e8-a2bb-000c29dcdf3d',
       'c8b68d5f-e0fa-11e9-a2da-000c29675a27',
       '43cff742-944d-11ea-ab37-000c29a01421',
       '44db5fa8-3bff-11e9-a2d4-000c29675a27',
       '2619b979-1c6d-11e4-8146-f46d04736e4a',
       'bd6d4fe5-0111-11e5-87f0-f46d04736e4a',
       '36640109-4387-11e8-a2bb-000c29dcdf3d',
       'fc73caca-d29a-11e8-a2c4-00505607eae9',
       '10f10f9e-c241-11e9-a2d7-000c29675a27',
       '487cc5f5-e8c8-11e9-a2dc-000c29675a27',
       '261db872-3e24-11e4-ae6f-f46d04736e4a',
       '1b38fc80-5d45-11ea-a307-00505607eae9',
       '287e2bf5-c066-11e7-ab58-000c2945f18b',
       '203e7502-9160-11e8-a2c6-000c29dcdf3d',
       '0fa38e6d-e5d0-11e9-a2db-000c29675a27',
       '180157c1-051c-11ea-a2e4-00505607eae9',
       '34082901-2188-11ea-a2f3-00505607eae9',
       '98344bcd-2bda-11e6-80cc-00155d000e07',
       'f70a6ab6-2186-11ea-a2f3-00505607eae9',
       'b8afaf51-3c0b-11ea-a2fd-00505607eae9',
       '456e02fa-46d9-11e9-a2d5-000c29675a27',
       'e77b64ff-5444-11e9-a2d5-000c29675a27',
       'cef6af8b-4bcd-11e9-a2d5-000c29675a27',
       '8f41e0c9-f40a-11ea-ab3c-000c29a0142b',
       'ead9ab2c-2e75-11e8-ab63-000c2945f18b',
       'aaf1855f-3436-11e9-a2ce-000c29675a27',
       'f7e3f2a0-ab07-11e4-b4a2-f46d04736e4a',
       '65e18c1c-6041-11e9-a2d6-000c29675a31',
       '5bbdf9fc-547a-11e9-a2d5-000c29675a27',
       '65212724-9c01-11ea-ab38-000c29a01421',
       '0fe08f06-a8d5-11e6-80d4-00155d000e07'], dtype=object)

In [144]:
# Отсортируем записи по дате поступления на склад
deliv = deliv.sort_values(by=['date_receipt'])

In [145]:
# Посмотрим на датасет
deliv.head(10)

,date_receipt,PlacementToId,date_orders,PlacementFromId,IsFromSupplier
88752,2020-09-19T00:00:00,03f70e82-3e4e-11e8-a2bb-000c29dcdf3d,2020-08-13T00:00:00,53898bbe-d2b7-11e8-a2c4-00505607eae9,1
88875,2020-09-19T00:00:00,5f219248-fadd-11df-8a53-00262d126e8b,2020-08-03T00:00:00,48452082-00c4-11e8-ab61-000c2945f18b,1
88876,2020-09-19T00:00:00,5f219248-fadd-11df-8a53-00262d126e8b,2020-07-03T00:00:00,48452082-00c4-11e8-ab61-000c2945f18b,1
88877,2020-09-19T00:00:00,f6548095-c106-11e0-8baa-00262d126e8b,2020-07-11T00:00:00,4038bae0-e7bc-11e6-80d6-00155d000e02,1
88878,2020-09-19T00:00:00,f6548095-c106-11e0-8baa-00262d126e8b,2020-07-06T00:00:00,f0287a2c-d6a6-11e4-891c-f46d04736e4a,1
88879,2020-09-19T00:00:00,f6548095-c106-11e0-8baa-00262d126e8b,2020-07-16T00:00:00,f0287a2c-d6a6-11e4-891c-f46d04736e4a,1
88880,2020-09-19T00:00:00,f6548095-c106-11e0-8baa-00262d126e8b,2020-07-26T00:00:00,f0287a2c-d6a6-11e4-891c-f46d04736e4a,1
88881,2020-09-19T00:00:00,f6548095-c106-11e0-8baa-00262d126e8b,2020-07-20T00:00:00,f0287a2c-d6a6-11e4-891c-f46d04736e4a,1
88882,2020-09-19T00:00:00,f6548095-c106-11e0-8baa-00262d126e8b,2020-08-05T00:00:00,86623a51-217a-11ea-a2f3-00505607eae9,1
88883,2020-09-19T00:00:00,f6548095-c106-11e0-8baa-00262d126e8b,2020-07-23T00:00:00,799adf67-cb79-11e6-80d4-00155d000e07,1

In [146]:
# Из типа объект делаем даты
object_to_date(deliv, deliv.date_receipt, 'date_receipt')
object_to_date(deliv, deliv.date_orders, 'date_orders')

In [147]:
# Создадим предиктор со сроками поставок
deliv['difference'] = deliv.date_receipt - deliv.date_orders

# Посмотрим результат
deliv.head(10)

,date_receipt,PlacementToId,date_orders,PlacementFromId,IsFromSupplier,difference
88752,2020-09-19,03f70e82-3e4e-11e8-a2bb-000c29dcdf3d,2020-08-13,53898bbe-d2b7-11e8-a2c4-00505607eae9,1,37 days
88875,2020-09-19,5f219248-fadd-11df-8a53-00262d126e8b,2020-08-03,48452082-00c4-11e8-ab61-000c2945f18b,1,47 days
88876,2020-09-19,5f219248-fadd-11df-8a53-00262d126e8b,2020-07-03,48452082-00c4-11e8-ab61-000c2945f18b,1,78 days
88877,2020-09-19,f6548095-c106-11e0-8baa-00262d126e8b,2020-07-11,4038bae0-e7bc-11e6-80d6-00155d000e02,1,70 days
88878,2020-09-19,f6548095-c106-11e0-8baa-00262d126e8b,2020-07-06,f0287a2c-d6a6-11e4-891c-f46d04736e4a,1,75 days
88879,2020-09-19,f6548095-c106-11e0-8baa-00262d126e8b,2020-07-16,f0287a2c-d6a6-11e4-891c-f46d04736e4a,1,65 days
88880,2020-09-19,f6548095-c106-11e0-8baa-00262d126e8b,2020-07-26,f0287a2c-d6a6-11e4-891c-f46d04736e4a,1,55 days
88881,2020-09-19,f6548095-c106-11e0-8baa-00262d126e8b,2020-07-20,f0287a2c-d6a6-11e4-891c-f46d04736e4a,1,61 days
88882,2020-09-19,f6548095-c106-11e0-8baa-00262d126e8b,2020-08-05,86623a51-217a-11ea-a2f3-00505607eae9,1,45 days
88883,2020-09-19,f6548095-c106-11e0-8baa-00262d126e8b,2020-07-23,799adf67-cb79-11e6-80d4-00155d000e07,1,58 days

In [148]:
# Выберем только количество 
# дней в сроках поставок
lst = []
for item in deliv.difference:
    lst.append(item.days)
deliv['delivery'] = lst

# Посмотрим информацию по датасету
deliv.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 71219 entries, 88752 to 159970
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date_receipt     71219 non-null  datetime64[ns]
 1   PlacementToId    71219 non-null  object
 2   date_orders      71219 non-null  datetime64[ns]
 3   PlacementFromId  71219 non-null  object
 4   IsFromSupplier   71219 non-null  int64
 5   difference       71219 non-null  timedelta64[ns]
 6   delivery         71219 non-null  int64
dtypes: datetime64[ns](2), int64(2), object(2), timedelta64[ns](1)
memory usage: 4.3+ MB

In [149]:
# Результат предыдущих операций
deliv.head()

,date_receipt,PlacementToId,date_orders,PlacementFromId,IsFromSupplier,difference,delivery
88752,2020-09-19,03f70e82-3e4e-11e8-a2bb-000c29dcdf3d,2020-08-13,53898bbe-d2b7-11e8-a2c4-00505607eae9,1,37 days,37
88875,2020-09-19,5f219248-fadd-11df-8a53-00262d126e8b,2020-08-03,48452082-00c4-11e8-ab61-000c2945f18b,1,47 days,47
88876,2020-09-19,5f219248-fadd-11df-8a53-00262d126e8b,2020-07-03,48452082-00c4-11e8-ab61-000c2945f18b,1,78 days,78
88877,2020-09-19,f6548095-c106-11e0-8baa-00262d126e8b,2020-07-11,4038bae0-e7bc-11e6-80d6-00155d000e02,1,70 days,70
88878,2020-09-19,f6548095-c106-11e0-8baa-00262d126e8b,2020-07-06,f0287a2c-d6a6-11e4-891c-f46d04736e4a,1,75 days,75

In [151]:
# # Сгруппируем датасет по производителям и складам, агрегирую сроки поставки процентилем
deliv_min = deliv.groupby(['PlacementFromId', 'PlacementToId', 'IsFromSupplier']).agg(
    {'delivery': percentile(50)}).reset_index()
deliv_max = deliv.groupby(['PlacementFromId', 'PlacementToId', 'IsFromSupplier']).agg(
    {'delivery': percentile(90)}).reset_index()

In [152]:
deliv_max['DaysTo'] = deliv_max.delivery
deliv_min['DaysFrom'] = deliv_min.delivery
deliv_max.drop('delivery', axis=1, inplace=True)
deliv_min.drop('delivery', axis=1, inplace=True)

In [153]:
statistics = pd.merge(
    deliv_max, deliv_min,
    on=['PlacementFromId', 'PlacementToId', 'IsFromSupplier'],
    how='left'
)
statistics

,PlacementFromId,PlacementToId,IsFromSupplier,DaysTo,DaysFrom
0,00000000-0000-0000-0000-000000000000,03f70e82-3e4e-11e8-a2bb-000c29dcdf3d,1,63.0,63.0
1,00000000-0000-0000-0000-000000000000,5f219248-fadd-11df-8a53-00262d126e8b,1,50.0,50.0
2,00bae129-1faf-11e9-a2c8-00505607eae9,03f70e82-3e4e-11e8-a2bb-000c29dcdf3d,1,67.3,37.0
3,00bae129-1faf-11e9-a2c8-00505607eae9,385b9ff4-cccf-11ea-ab39-000c29a0142b,1,53.8,51.0
4,00bae129-1faf-11e9-a2c8-00505607eae9,4bc4d898-ec0e-11e9-a2dc-000c29675a27,1,59.8,39.0
...,...,...,...,...,...
1511,fed611d8-cb93-11e4-b853-f46d04736e4a,03f70e82-3e4e-11e8-a2bb-000c29dcdf3d,1,62.3,54.0
1512,fed611d8-cb93-11e4-b853-f46d04736e4a,5f219248-fadd-11df-8a53-00262d126e8b,1,63.0,48.0
1513,fed611d8-cb93-11e4-b853-f46d04736e4a,a2f89531-75de-11e8-a2c3-000c29dcdf3d,1,67.2,56.0
1514,fed611d8-cb93-11e4-b853-f46d04736e4a,f6548095-c106-11e0-8baa-00262d126e8b,1,91.0,65.0
1515,ff5ec777-c749-11ea-ab38-000c29a01421,f6548095-c106-11e0-8baa-00262d126e8b,1,51.0,51.0

In [154]:
statistics.to_json('statistics.json', orient="split")
statistics.to_excel('statistics.xlsx', index=False)

### To be continued...

In [155]:
deliv

,date_receipt,PlacementToId,date_orders,PlacementFromId,IsFromSupplier,difference,delivery
88752,2020-09-19,03f70e82-3e4e-11e8-a2bb-000c29dcdf3d,2020-08-13,53898bbe-d2b7-11e8-a2c4-00505607eae9,1,37 days,37
88875,2020-09-19,5f219248-fadd-11df-8a53-00262d126e8b,2020-08-03,48452082-00c4-11e8-ab61-000c2945f18b,1,47 days,47
88876,2020-09-19,5f219248-fadd-11df-8a53-00262d126e8b,2020-07-03,48452082-00c4-11e8-ab61-000c2945f18b,1,78 days,78
88877,2020-09-19,f6548095-c106-11e0-8baa-00262d126e8b,2020-07-11,4038bae0-e7bc-11e6-80d6-00155d000e02,1,70 days,70
88878,2020-09-19,f6548095-c106-11e0-8baa-00262d126e8b,2020-07-06,f0287a2c-d6a6-11e4-891c-f46d04736e4a,1,75 days,75
...,...,...,...,...,...,...,...
159471,2020-12-17,f6548095-c106-11e0-8baa-00262d126e8b,2020-11-18,d86359ec-e37f-11ea-ab3c-000c29a0142b,1,29 days,29
159472,2020-12-17,f6548095-c106-11e0-8baa-00262d126e8b,2020-11-29,d86359ec-e37f-11ea-ab3c-000c29a0142b,1,18 days,18
159473,2020-12-17,f6548095-c106-11e0-8baa-00262d126e8b,2020-12-10,d86359ec-e37f-11ea-ab3c-000c29a0142b,1,7 days,7
159464,2020-12-17,4bc4d898-ec0e-11e9-a2dc-000c29675a27,2020-10-15,9850e147-7c17-11e7-ab50-000c2945f18b,1,63 days,63
159970,2020-12-17,f6548095-c106-11e0-8baa-00262d126e8b,2020-11-27,6e75c97a-b7de-11e7-ab58-000c2945f18b,1,20 days,20

In [157]:
deliv.to_csv('delivery_time.csv', index=False)